### ISSUE TITLE
Step is ignored:

### ISSUE THREAD

**Issue by jimijon** [SwiftUIExtensions/Sliders#91]
HSlider(
                        value: $stateVal,
                        in: lBound...uBound,
                        step: step,
                        track: Rectangle().foregroundColor(Color("TPOrange")).frame(height: 3),
                        onEditingChanged: {value in
                            if !value {
                                self.queryCallback()
                        }
                    })

I am sending 0.5 as a step but it is only displaying whole values.

**Comment by ay42** [comment]
@jimijon Just tested it and it's working as expected. Gives half value steps 1.5...2.0...2.5.
```swift
@State var value1 = 1.0
...
HSlider(value: $value1, in: 0...400, step: 0.5, track: Rectangle().foregroundColor(.orange).frame(height: 3))
Text("\(value1)")
```
