### ISSUE TITLE
Add .onEnd 

### ISSUE THREAD

**Issue by jimijon** [SwiftUIExtensions/Sliders#92]
For performance reasons, I need to grab and update the final values. You send the events which is good, I just need the onEnd event to update a different part of the page.

**Comment by ay42** [comment]
@jimijon You can update when `onEditingChanged` sends `false` and take a latest value from a binding. This will you will only update once. Will this work for you?

**Comment by jimijon** [comment]
It doesn’t. I tried. It keeps firing false too as you move. SwiftUI is a bit slow, so my value of the thumb is not quite the same as being shown in a different part of the view. I want to shut off that until it is finished moving.

**Comment by ay42** [comment]
@jimijon We are trying to match an API of SwiftUI native slider so we will not be adding this callback but you can achieve this without `onEditingChanged` callback even.
Use `Combine` to listen to values overtime on a value binding and `throttle` is to 0.5 seconds. This will give you the behaviour you are looking for.

**Comment by jimijon** [comment]
OK.  Makes good sense about the API. Thanks for the prompt response. I will use your recommended approach.
